// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WepAPI_DB.Entities;

#nullable disable

namespace WepAPI_DB.Migrations
{
    [DbContext(typeof(WebAPIContext))]
    [Migration("20221117142747_third")]
    partial class third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WepAPI_DB.Kisi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CinsiyetKisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TC")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TC")
                        .IsUnique();

                    b.ToTable("Kisiler");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            Ad = "Tolga",
                            CinsiyetKisi = 0,
                            DogumTarihi = new DateTime(1992, 11, 17, 17, 27, 47, 177, DateTimeKind.Local).AddTicks(1856),
                            Soyad = "SERTKAYA",
                            TC = 11111
                        },
                        new
                        {
                            ID = 7,
                            Ad = "Onur Alp",
                            CinsiyetKisi = 0,
                            DogumTarihi = new DateTime(1994, 11, 17, 17, 27, 47, 177, DateTimeKind.Local).AddTicks(1869),
                            Soyad = "AYDIN",
                            TC = 22222
                        },
                        new
                        {
                            ID = 4,
                            Ad = "Cenk",
                            CinsiyetKisi = 1,
                            DogumTarihi = new DateTime(1990, 11, 17, 17, 27, 47, 177, DateTimeKind.Local).AddTicks(1872),
                            Soyad = "TANKSOYLU",
                            TC = 33333
                        },
                        new
                        {
                            ID = 5,
                            Ad = "Oğuzhan",
                            CinsiyetKisi = 1,
                            DogumTarihi = new DateTime(1990, 11, 17, 17, 27, 47, 177, DateTimeKind.Local).AddTicks(1873),
                            Soyad = "BAYRAM",
                            TC = 44444
                        },
                        new
                        {
                            ID = 6,
                            Ad = "Tarık",
                            CinsiyetKisi = 0,
                            DogumTarihi = new DateTime(1984, 11, 17, 17, 27, 47, 177, DateTimeKind.Local).AddTicks(1875),
                            Soyad = "AYDIN",
                            TC = 77777
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
